Repository fastruby/points, pull requests merged in 2021-11, with the labels that each got.

#122 Increase line height to prevent title overlap
  app/assets/stylesheets/2-quarks/_custom_typography.scss
Labels: hacktoberfest-accepted

#128 Update docker config files and readme
  Dockerfile
  README.md
  docker-compose.yml
Labels: Ready to QA

#120 Fix error when editing two or more estimates
  app/views/estimates/_update_estimates.js.erb
  app/views/estimates/_update_row.js.erb
  app/views/estimates/create.js.erb
  spec/features/estimates_manage_spec.rb
Labels: Ready to QA, hacktoberfest-accepted

#130 Update the title for projects to make more sense.
  app/views/projects/index.html.erb
Labels: Ready to Merge

#135 Initialize position on creation and fix order issue for duplicated positions
  app/controllers/action_plans_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/real_scores_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/stories_controller.rb
  app/models/report.rb
  app/models/story.rb
  spec/features/stories_manage_spec.rb
Labels: Ready to QA

#144 Adjust css layout to better position fixed headers and footer
  app/assets/stylesheets/2-quarks/_custom_typography.scss
  app/assets/stylesheets/application.scss
  app/views/layouts/application.html.erb
  app/views/projects/show.html.erb
Labels: Ready to Merge
